### ISSUE TITLE
BADGE REQUEST [Darkuss#9279]

### ISSUE THREAD

**Issue by Delta-official** [Discord-Theme-Addons/name-badges#100]
**What is your Discord Tag?**
Darkuss#9279

**What is your UID (User ID)?**
508632222245322793

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/qdnmnsH.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done!
