### ISSUE TITLE
BADGE REQUEST [USERNAME#0001]

### ISSUE THREAD

**Issue by rodrifelix99** [Discord-Theme-Addons/name-badges#101]
**What is your Discord Tag?**
Felix#2575
**What is your UID (User ID)?**
319542274373582848

**What is the image for the badge that you want? 
https://cdn.discordapp.com/attachments/831900279737810998/842334249985507348/sdfsdfsdfs.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
this badge wont appear properly, width is too long
