### ISSUE TITLE
BADGE REQUEST [Void#8844]

### ISSUE THREAD

**Issue by Void48** [Discord-Theme-Addons/name-badges#103]
**What is your Discord Tag?**
Void#8844

**What is your UID (User ID)?**
605764872856403978

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/0zLljHh.png

**Additional Confirmation:** 

- [x] My badge does not contain any NSFW material. 

- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done.
