### ISSUE TITLE
BADGE REQUEST [BeatCoin.ᵛ³#3440]

### ISSUE THREAD

**Issue by cilgintebesir** [Discord-Theme-Addons/name-badges#104]
**What is your Discord Tag?**
BeatCoin.ᵛ³#3440

**What is your UID (User ID)?**
836737917870669855

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/d352wBt.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done.

**Comment by cilgintebesir** [comment]
> done.

hey, background appears white can you fix it?
and pls make a little bit smaller

**Comment by LuckFire** [comment]
the background appears white because that's how the image is, there is no transparent background
as for sizing, nothing i can do about that (at least currently) since every badge goes by the same padding. will see if i can do something in the future about this.

**Comment by cilgintebesir** [comment]
oh sry. here is the new one
https://i.imgur.com/Js8OvpS.png

**Comment by LuckFire** [comment]
updated.
