### ISSUE TITLE
BADGE REQUEST [Twui#7050]

### ISSUE THREAD

**Issue by bakabakabakabakabaka** [Discord-Theme-Addons/name-badges#105]
**What is your Discord Tag?**
Twui#7050

**What is your UID (User ID)?**
528013844165951509

**What is the image for the badge that you want?**
https://cdn.discordapp.com/emojis/596576796594667521.png?size=64

**Additional Confirmation:** 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.
- [x] My badge does not contain any NSFW material.

**Comment by LuckFire** [comment]
done
