### ISSUE TITLE
BADGE REQUEST [LossLofi#3109]

### ISSUE THREAD

**Issue by LossYoutube** [Discord-Theme-Addons/name-badges#106]
**What is your Discord Tag?**
LossLofi#3109

**What is your UID (User ID)?**
842526957697630258

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/avatars/842526957697630258/6474dfb8e7357752b767d9ffd3c01c24.png?size=1024

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. (It does not.)
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities. (It does not.)

**Comment by LuckFire** [comment]
image does not exist.
