### ISSUE TITLE
BADGE REQUEST [Geshi#0001]

### ISSUE THREAD

**Issue by geshii** [Discord-Theme-Addons/name-badges#107]
**What is your Discord Tag?**
Geshi#0001

**What is your UID (User ID)?**
329498023103037440

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/attachments/845711091647774733/846356653934379046/thing.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
