### ISSUE TITLE
BADGE REQUEST [Zyy#8672]

### ISSUE THREAD

**Issue by Zykkl** [Discord-Theme-Addons/name-badges#109]
**What is your Discord Tag?**
Zyy#8672

**What is your UID (User ID)?**
673634598441320449

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/attachments/809099404665290772/810974679417880596/746115934518902825.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material.
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
