### ISSUE TITLE
BADGE REQUEST [Enzo | Flaminou#7519]

### ISSUE THREAD

**Issue by Flaminouu** [Discord-Theme-Addons/name-badges#110]
**What is your Discord Tag?**
Enzo | Flaminou#7519

**What is your UID (User ID)?**
637199008296730643

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://media.discordapp.net/attachments/663172781126713364/847076147652591616/3957_diamond_light-0.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
