### ISSUE TITLE
BADGE REQUEST [JustDaikø ⬘#7284]

### ISSUE THREAD

**Issue by DaikoCode3** [Discord-Theme-Addons/name-badges#112]
**What is your Discord Tag?**
JustDaikø ⬘#7284

**What is your UID (User ID)?**
479329019716960256

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://imgur.com/olkBidY.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
