### ISSUE TITLE
UPDATE BADGE REQUEST [MintLily#0001]

### ISSUE THREAD

**Issue by MintLily** [Discord-Theme-Addons/name-badges#113]
**What is your Discord Tag?**
Old: `KortyBoi#0001`
New: `MintLily#0001`

**What is your UID (User ID)?**
167335587488071682

**What is the image for the badge that you want?**
https://i.imgur.com/YxjUfJC.png

**Additional Confirmation:** 
✔️ My badge does not contain any NSFW material. 
✔️ My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
