### ISSUE TITLE
BADGE REQUEST [cancaze#0513]

### ISSUE THREAD

**Issue by xCancazedd** [Discord-Theme-Addons/name-badges#114]
**What is your Discord Tag?**
cancaze#0513

**What is your UID (User ID)?**
734884434225922120

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***

https://media.discordapp.net/attachments/847785763621699584/848373164546850816/small.jpg
**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
