### ISSUE TITLE
UPDATE BADGE REQUEST [Darkuss#3803]

### ISSUE THREAD

**Issue by Delta-official** [Discord-Theme-Addons/name-badges#115]
**What is your Discord Tag?**
OLD: `Darkuss#9279`
NEW: `Darkuss#3803`

**What is your UID (User ID)?**
770804101332074547

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
Same as before

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by Delta-official** [comment]
@LuckFire

**Comment by LuckFire** [comment]
done

**Comment by Delta-official** [comment]
thank you
