### ISSUE TITLE
BADGE REQUEST [• Hawks • 🌈#1337]

### ISSUE THREAD

**Issue by Official-Hawks** [Discord-Theme-Addons/name-badges#117]
**What is your Discord Tag?**
• Hawks • 🌈#1337

**What is your UID (User ID)?**
811770910624579584

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as https://cdn.discordapp.com/attachments/843160047093153822/851642648438636574/circle-cropped.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
