### ISSUE TITLE
BADGE REQUEST [ceg#6014]

### ISSUE THREAD

**Issue by Vzurxy** [Discord-Theme-Addons/name-badges#118]
**What is your Discord Tag?**
ceg#6014

**What is your UID (User ID)?**
546868093603807233

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***

https://i.imgur.com/CHSXvTG.png
- (512x512, should be able to be downscaled)

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
