### ISSUE TITLE
BADGE REQUEST [Abderian#7053]

### ISSUE THREAD

**Issue by GroupSizzlin** [Discord-Theme-Addons/name-badges#119]
**What is your Discord Tag?**
Abderian#7053

**What is your UID (User ID)?**
846641328342302760

https://i.imgur.com/uL3hpgn.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
