### ISSUE TITLE
BADGE REQUEST [kixti#2021]

### ISSUE THREAD

**Issue by kixt0** [Discord-Theme-Addons/name-badges#120]
**What is your Discord Tag?**
kixti#2021

**What is your UID (User ID)?**
452289159399342090

https://i.imgur.com/puXZWLQ.gif

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
