### ISSUE TITLE
BADGE REQUEST [Oalo#7117]

### ISSUE THREAD

**Issue by MudkipBanana** [Discord-Theme-Addons/name-badges#121]
**What is your Discord Tag?**
Oalo#7117

**What is your UID (User ID)?**
743606486063644673

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/vYyV7hU.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
