### ISSUE TITLE
BADGE REQUEST [USERNAME#0001]

### ISSUE THREAD

**Issue by FakeValentine** [Discord-Theme-Addons/name-badges#91]
**What is your Discord Tag?**
FValentine#0881

**What is your UID (User ID)?**
452802233277612052

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
![K6sJdAM](https://user-images.githubusercontent.com/83130749/115964610-9fe6ad00-a525-11eb-8552-8dcddd1079bc.png)

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by HooferDevelops** [comment]
Added!
