### ISSUE TITLE
BADGE REQUEST [Sadooor#5579]

### ISSUE THREAD

**Issue by sadooor** [Discord-Theme-Addons/name-badges#93]
**What is your Discord Tag?**
Sadooor#5579

**What is your UID (User ID)?**
604968093181018112

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/attachments/835462212130045982/835462273573191720/image1.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by HooferDevelops** [comment]
Added!

**Comment by sadooor** [comment]
> Added!

thanks
