### ISSUE TITLE
BADGE REQUEST [Nyria#3863]

### ISSUE THREAD

**Issue by NYRI4** [Discord-Theme-Addons/name-badges#94]
**What is your Discord Tag?**
Nyria#3863

**What is your UID (User ID)?**
265924886461939712

**What is the image for the badge that you want?**
https://i.imgur.com/SsYHmfp.gif

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by HooferDevelops** [comment]
Added!
