### ISSUE TITLE
BADGE REQUEST [PhoenixAceVFX#6501]

### ISSUE THREAD

**Issue by PhoenixAceVFX** [Discord-Theme-Addons/name-badges#95]
**What is your Discord Tag?**
PhoenixAceVFX#6501

**What is your UID (User ID)?**
461440763042201620

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/attachments/461441240395808798/838704939064098866/Vanessa.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done!
