### ISSUE TITLE
BADGE REQUEST [VeX#2764]

### ISSUE THREAD

**Issue by Vexnass** [Discord-Theme-Addons/name-badges#98]
**What is your Discord Tag?**
VeX#2764

**What is your UID (User ID)?**
105036577511632896

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.*** https://emoji.gg/emoji/5492_EzPepe

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
this is not a cdn.discordapp link or imgur link
