### ISSUE TITLE
BADGE REQUEST [Avile#8008]

### ISSUE THREAD

**Issue by AvileCoder** [Discord-Theme-Addons/name-badges#99]
**What is your Discord Tag?**
Avile#8008

**What is your UID (User ID)?**
572811135305252895

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/avatars/572811135305252895/5a150fecee877cd0da2f5c6901e4106f.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. [AGREE]
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities. [AGREE]

**Comment by LuckFire** [comment]
done!
